### ISSUE TITLE
Add create command?

### ISSUE THREAD

**Issue by Coolumin** [KilLo445/extract-xiso-gui#1]
It does seem like an odd omission. I personally use extract-xiso's create command quite a bit, so it would be appreciated if this was added.

**Comment by KilLo445** [comment]
I'll see what I can do, thanks for the suggestion, should be out soon!

**Comment by KilLo445** [comment]
I have released the update, https://github.com/KilLo445/extract-xiso-gui/releases/latest

**Comment by Coolumin** [comment]
Nice, glad to see it.

**Comment by KilLo445** [comment]
> browsing for the folder still wants me to select an ISO instead of a folder

Leave the first browse path empty and just hit go, it opens another window with the folder select, it's kinda half-assed lol
