### ISSUE TITLE
[Feature Req] Batch functionality

### ISSUE THREAD

**Issue by Coolumin** [KilLo445/extract-xiso-gui#2]
**Is your feature request related to a problem? Please describe.**
Since this is the only FOSS GUI for extract-xiso, it would be good if it was feature complete with the other GUIs for this application alongside the application itself. One of the features that [this GUI](https://digiex.net/threads/xbox-360-xiso-extract-best-an-easiest-xdg3-extraction-tool-with-gui-ftp.9711/) includes but isn't in this app is batch management of ISOs, which isn't featured in this GUI. However, it is a feature of extract-xiso itself.

**Describe the solution you'd like**
Have the app keep a list of each ISO or folder you add to the application, and then all of them will be managed once you hit the GO button.

**Describe alternatives you've considered** 
[This GUI](https://digiex.net/threads/xbox-360-xiso-extract-best-an-easiest-xdg3-extraction-tool-with-gui-ftp.9711/) does work, but it has limited features because it's only intended for extracting ISOs.

**Comment by KilLo445** [comment]
Added in [v1.2.0](https://github.com/KilLo445/extract-xiso-gui/releases/tag/1.2.0)

**Comment by Coolumin** [comment]
> Added in [v1.2.0](https://github.com/KilLo445/extract-xiso-gui/releases/tag/1.2.0)

Pretty cool, although it seems odd the extract command doesn't have batch functionality too.

**Comment by KilLo445** [comment]
> Pretty cool, although it seems odd the extract command doesn't have batch functionality too.

Does it not? I honestly thought I added it

**Comment by Coolumin** [comment]
> > Pretty cool, although it seems odd the extract command doesn't have batch functionality too.
> 
> Does it not? I honestly thought I added it

I guess not. The batch feature only works with the rebuild command; the others only allow for single file selection.

**Comment by IAmNadaman** [comment]
> > Pretty cool, although it seems odd the extract command doesn't have batch functionality too.
> 
> Does it not? I honestly thought I added it

Actually, I see what's going on now. Batch functionality with the extract command requires you to specify a folder rather than multiple files. So implementing that in the GUI while still allowing for single file selection would probably need a checkbox to specify that mode or something.
